---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template

- name: VM from template
#  hosts: vmcreate
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: vcsa.box
    esxhost: 172.28.20.112
    datastore: NexentaStor1
    network: TRUNK
    vmtemplate: Template_Centos72
    vmcluster: HA_Cluster
    notes: Created by Ansible
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: TestDC
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
          - name: "{{ network }}"
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"

